import { readThread } from '../core/thread.js';
import { writeFile, huddleupPath, fileExists } from '../core/files.js';
import { readCharter } from '../core/charter.js';
import { openFiles } from '../utils/editor.js';
import { extractFilePaths } from '../adapters/base.js';
import { colors } from '../utils/colors.js';
import * as logger from '../utils/logger.js';

export async function resume(threadName: string): Promise<void> {
  logger.header('HuddleUp - Resume');

  const thread = readThread(threadName);
  if (!thread) {
    logger.error(`Thread "${threadName}" not found.`);
    logger.info('Run "huddleup thread list" to see available threads.');
    process.exit(1);
  }

  const charter = readCharter();

  logger.brief([
    colors.bold('  YOU ARE HERE'),
    '',
    `  Thread: ${colors.highlight(thread.meta.title)}`,
    `  Owner:  ${thread.meta.owner}`,
    `  Status: ${thread.meta.status}`,
    `  Last update: ${thread.meta.updated.slice(0, 19).replace('T', ' ')}`,
    thread.meta.lastNote ? `  Last note: "${thread.meta.lastNote}"` : '',
  ].filter(Boolean));

  // Print the most recent snapshot block
  const snapshots = thread.content.split(/^## Snapshot[ \-—]/m);
  if (snapshots.length > 1) {
    const latest = snapshots[snapshots.length - 1].trim();
    const lines = latest.split('\n').slice(0, 16);
    console.log('\n' + lines.map((l) => `  ${l}`).join('\n'));
  }

  logger.divider();

  if (charter) {
    console.log(colors.bold('\n  Project Context:'));
    if (charter.stack) console.log(`  Stack: ${charter.stack.split('\n').slice(0, 3).join(' | ').slice(0, 200)}`);
    if (charter.conventions) console.log(`  Conventions: ${charter.conventions.split('\n').slice(0, 3).join(' | ').slice(0, 200)}`);
    logger.divider();
  }

  // Reopen relevant files (now safe + extracted with the shared regex)
  const candidates = extractFilePaths(thread.content.split('\n'), 20);
  const existing = candidates.filter((f) => fileExists(f));
  if (existing.length > 0) {
    console.log(colors.bold('\n  Opening relevant files:'));
    for (const f of existing.slice(0, 5)) console.log(`    ${f}`);
    openFiles(existing.slice(0, 5));
  }

  // Write a context file the AI tool can read
  const contextPath = huddleupPath('resume-context.md');
  const contextContent = [
    `# Resumed Context: ${thread.meta.title}`,
    '',
    `Resuming work on "${thread.meta.title}". Most recent state below.`,
    '',
    '## Most Recent Snapshot',
    thread.content.split(/^## Snapshot[ \-—]/m).pop()?.trim() || '(no snapshot yet)',
    '',
    '## Charter Context',
    charter?.raw || 'No charter configured.',
    '',
    '---',
    '*Generated by HuddleUp resume.*',
  ].join('\n');
  writeFile(contextPath, contextContent);

  logger.success('Context written to .huddleup/resume-context.md');
  logger.info(colors.dim("You're all set. Continue where your teammate left off."));
}
