import { readThread } from '../core/thread.js';
import { readFile, huddleupPath, fileExists } from '../core/files.js';
import { readCharter } from '../core/charter.js';
import { openFiles } from '../utils/editor.js';
import { colors } from '../utils/colors.js';
import * as logger from '../utils/logger.js';

export async function resume(threadName: string): Promise<void> {
  logger.header('HuddleUp — Resume');

  const thread = readThread(threadName);
  if (!thread) {
    logger.error(`Thread "${threadName}" not found.`);
    logger.info(`Run "huddleup thread list" to see available threads.`);
    process.exit(1);
  }

  const charter = readCharter();

  // Print "YOU ARE HERE" briefing
  logger.brief([
    colors.bold('  YOU ARE HERE'),
    '',
    `  Thread: ${colors.highlight(threadName)}`,
    '',
  ]);

  // Extract snapshots from thread content
  const snapshots = thread.content.split('## Snapshot —');
  if (snapshots.length > 1) {
    const latest = snapshots[snapshots.length - 1].trim();
    const lines = latest.split('\n').filter(l => l.trim());
    for (const line of lines.slice(0, 10)) {
      console.log(`  ${line}`);
    }
  } else {
    console.log(`  ${thread.content.slice(0, 500)}`);
  }

  logger.divider();

  // Show project context
  if (charter) {
    console.log(colors.bold('\n  Project Context:'));
    if (charter.stack) console.log(`  Stack: ${charter.stack.slice(0, 200)}`);
    if (charter.conventions) console.log(`  Conventions: ${charter.conventions.slice(0, 200)}`);
    logger.divider();
  }

  // Find files mentioned in the thread
  const fileMentions = thread.content.match(/[\w-/]+\.\w+/g) || [];
  const uniqueFiles = [...new Set(fileMentions)].filter(f => fileExists(f));

  if (uniqueFiles.length > 0) {
    console.log(colors.bold('\n  Opening relevant files...'));
    openFiles(uniqueFiles.slice(0, 5));
  }

  // Inject context into AI tool files
  const contextPath = huddleupPath('resume-context.md');
  const contextContent = [
    `# Resumed Context: ${threadName}`,
    '',
    `This session resumes work from "${threadName}".`,
    '',
    '## Last Snapshot',
    thread.content.split('## Snapshot —').pop()?.trim() || '',
    '',
    '## Charter Context',
    charter?.raw || 'No charter configured.',
    '',
    '---',
    '*Generated by HuddleUp resume*',
  ].join('\n');
  // The context is written to a temp file; the generated AI tool files (CLAUDE.md etc.)
  // reference .huddleup/ as the source of truth, so the AI reads it naturally.
  const { writeFile } = await import('../core/files.js');
  writeFile(contextPath, contextContent);

  logger.success('Context injected into session');
  logger.info(colors.dim('\nYou\'re all set. Continue where your teammate left off.'));
}
